import fs from 'fs';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { config } from '../config/env';

const execFileAsync = promisify(execFile);

function getFilePath() {
  return process.env.NGINX_DENY_FILE || config.NGINX_DENY_FILE;
}

export async function addDeny(ip: string): Promise<boolean> {
  try {
    const path = getFilePath();
    let content = '';
    if (fs.existsSync(path)) {
      content = fs.readFileSync(path, 'utf8');
    } else {
      content = '# Auto-generated by IDS\n';
    }
    const line = `deny ${ip};`;
    if (!content.split('\n').some(l => l.trim() === line)) {
      content += (content.endsWith('\n') ? '' : '\n') + line + '\n';
      fs.mkdirSync(require('path').dirname(path), { recursive: true });
      fs.writeFileSync(path, content, 'utf8');
    }
    return true;
  } catch (e) {
    console.error('nginx addDeny failed:', e);
    return false;
  }
}

export async function removeDeny(ip: string): Promise<boolean> {
  try {
    const path = getFilePath();
    if (!fs.existsSync(path)) return true;
    const line = `deny ${ip};`;
    const updated = fs.readFileSync(path, 'utf8')
      .split('\n')
      .filter(l => l.trim() !== line)
      .join('\n');
    fs.writeFileSync(path, updated, 'utf8');
    return true;
  } catch (e) {
    console.error('nginx removeDeny failed:', e);
    return false;
  }
}

export async function reloadNginxIfConfigured(): Promise<void> {
  try {
    const cmd = process.env.NGINX_RELOAD_CMD || config.NGINX_RELOAD_CMD;
    if (!cmd) return;
    await execFileAsync('sh', ['-lc', cmd]);
  } catch (e) {
    console.error('nginx reload failed:', e);
  }
}